services:
  vapourtron_be:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
  db:
    image: postgres:17
    restart: unless-stopped
    volumes:
      - /var/db/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
